spring.application.name=api-gateway
server.port=8080

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=scooter-service
spring.cloud.gateway.routes[1].uri=lb://scooter-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/scooters/**

spring.cloud.gateway.routes[2].id=trip-service
spring.cloud.gateway.routes[2].uri=lb://trip-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/trips/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/