spring.application.name=user-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=yura
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=7vJm3X2pQ9kL8rT1yN4aB6cD0eF5gH2jK9mP3sW1xZ8qR6uT4vY2nM7bC1dE5fG

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/v1/changelog-master.yaml
